<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FormFieldsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('form_fields')->delete();
        
        \DB::table('form_fields')->insert(array (
            0 => 
            array (
                'id' => 4,
                'form_section_id' => 3,
                'label' => 'Sport',
                'name' => 'sport',
                'type' => 'select',
                'options' => '["Football","Basketball","Volleyball","Netball","Handball","Cricket","Table Tennis","Badminton","Tennis","Swimming","Athletics","Surfing"]',
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 4,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 07:12:55',
                'updated_at' => '2025-09-17 07:16:32',
                'class_name' => NULL,
                'placeholder' => 'Select Sport',
            ),
            1 => 
            array (
                'id' => 1,
                'form_section_id' => 3,
                'label' => 'Name',
                'name' => 'name',
                'type' => 'text',
                'options' => 'null',
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 1,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-16 07:43:03',
                'updated_at' => '2025-09-17 07:17:48',
                'class_name' => 'col-span-6',
                'placeholder' => 'Full Name',
            ),
            2 => 
            array (
                'id' => 2,
                'form_section_id' => 3,
                'label' => 'Club Name',
                'name' => 'club_name',
                'type' => 'text',
                'options' => 'null',
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 2,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-16 07:43:38',
                'updated_at' => '2025-09-17 07:17:58',
                'class_name' => NULL,
                'placeholder' => 'Club Name',
            ),
            3 => 
            array (
                'id' => 3,
                'form_section_id' => 3,
                'label' => 'Position in Club',
                'name' => 'club_position',
                'type' => 'select',
                'options' => '["President","Vice President","Secretary","Organising Secretary","Treasurer","Support Staff"]',
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 3,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 06:47:01',
                'updated_at' => '2025-09-17 07:18:15',
                'class_name' => NULL,
                'placeholder' => 'Select Position',
            ),
            4 => 
            array (
                'id' => 5,
                'form_section_id' => 3,
                'label' => 'Street Address',
                'name' => 'address',
                'type' => 'text',
                'options' => NULL,
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 5,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 07:20:14',
                'updated_at' => '2025-09-17 07:20:14',
                'class_name' => NULL,
                'placeholder' => 'House/Apartment, Road',
            ),
            5 => 
            array (
                'id' => 6,
                'form_section_id' => 3,
                'label' => 'Island/ City',
                'name' => 'island',
                'type' => 'select',
                'options' => '["Mal\\u00e9 City","Addu City","Fuvahmulah City","Kulhudhuffushi City","Th. Thimarafushi","V. Felidhoo","Hdh. Hanimaadhoo"]',
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 6,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 07:23:09',
                'updated_at' => '2025-09-17 07:23:09',
                'class_name' => NULL,
                'placeholder' => 'Select Island/ City',
            ),
            6 => 
            array (
                'id' => 7,
                'form_section_id' => 3,
                'label' => 'Contact Number',
                'name' => 'contact_no',
                'type' => 'tel',
                'options' => NULL,
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 7,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 07:31:42',
                'updated_at' => '2025-09-17 07:34:25',
                'class_name' => 'col-span-2',
                'placeholder' => 'Contact Number',
            ),
            7 => 
            array (
                'id' => 8,
                'form_section_id' => 3,
                'label' => 'Email',
                'name' => 'email',
                'type' => 'email',
                'options' => NULL,
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 8,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 07:32:43',
                'updated_at' => '2025-09-17 07:34:34',
                'class_name' => 'col-span-4',
                'placeholder' => 'Email',
            ),
            8 => 
            array (
                'id' => 9,
                'form_section_id' => 3,
                'label' => 'Website',
                'name' => 'website',
                'type' => 'url',
                'options' => NULL,
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 9,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 07:35:30',
                'updated_at' => '2025-09-17 07:35:30',
                'class_name' => 'col-span-6',
                'placeholder' => 'Club Website',
            ),
            9 => 
            array (
                'id' => 10,
                'form_section_id' => 5,
                'label' => 'Does your club have a clubhouse or purpose built facility?',
                'name' => 'has_clubhouse',
                'type' => 'radio',
                'options' => '["Yes","No"]',
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 1,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 08:46:40',
                'updated_at' => '2025-09-17 08:46:40',
                'class_name' => 'col-span-6',
                'placeholder' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'form_section_id' => 5,
                'label' => 'If not, where do you train/complete?',
                'name' => 'training_loc',
                'type' => 'text',
                'options' => NULL,
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 2,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 08:51:58',
                'updated_at' => '2025-09-17 08:51:58',
                'class_name' => 'col-span-6',
                'placeholder' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'form_section_id' => 5,
                'label' => 'Are the facilities available accessible to all?',
                'name' => 'is_accessible',
                'type' => 'radio',
                'options' => '["Yes","No"]',
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 3,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 08:54:12',
                'updated_at' => '2025-09-17 08:54:12',
                'class_name' => 'col-span-6',
                'placeholder' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'form_section_id' => 5,
                'label' => 'Is it available for hire?',
                'name' => 'is_hirable',
                'type' => 'radio',
                'options' => '["Yes","No"]',
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 4,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 08:54:38',
                'updated_at' => '2025-09-17 08:54:38',
                'class_name' => 'col-span-6',
                'placeholder' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'form_section_id' => 6,
                'label' => 'Does your club provide coaching?',
                'name' => 'has_coaching',
                'type' => 'radio',
                'options' => '["Yes","No"]',
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 1,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 08:55:33',
                'updated_at' => '2025-09-17 08:55:33',
                'class_name' => 'col-span-6',
                'placeholder' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'form_section_id' => 6,
                'label' => 'How many coaches do you have?',
                'name' => 'coach_num',
                'type' => 'number',
                'options' => NULL,
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 2,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 08:57:46',
                'updated_at' => '2025-09-17 08:57:46',
                'class_name' => 'col-span-6',
                'placeholder' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'form_section_id' => 6,
                'label' => 'What level of qualifications do your coaches have?',
                'name' => 'coach_qualification',
                'type' => 'textarea',
                'options' => NULL,
                'validation_rules' => 'null',
                'is_required' => false,
                'order' => 3,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 09:01:51',
                'updated_at' => '2025-09-17 09:01:51',
                'class_name' => 'col-span-12',
                'placeholder' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'form_section_id' => 7,
                'label' => 'What level does your club participate?',
                'name' => 'club_level',
                'type' => 'checkbox',
            'options' => '["Social\\/Recreation","Competitive (Friendly)","Competitive (Local League)","Competitive (National)"]',
                'validation_rules' => 'null',
                'is_required' => true,
                'order' => 1,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 09:06:19',
                'updated_at' => '2025-09-17 09:07:39',
                'class_name' => 'col-span-12',
                'placeholder' => NULL,
            ),
            17 => 
            array (
                'id' => 19,
                'form_section_id' => 7,
            'label' => 'What is the monthly cost of membership? (MVR)?',
                'name' => 'membership_cost',
                'type' => 'number',
                'options' => NULL,
                'validation_rules' => 'null',
                'is_required' => false,
                'order' => 3,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 09:51:50',
                'updated_at' => '2025-09-17 09:51:50',
                'class_name' => 'col-span-6',
                'placeholder' => NULL,
            ),
            18 => 
            array (
                'id' => 18,
                'form_section_id' => 7,
                'label' => 'What days does your club train on?',
                'name' => 'training_days',
                'type' => 'text',
                'options' => NULL,
                'validation_rules' => 'null',
                'is_required' => false,
                'order' => 2,
                'depends_on_field_id' => NULL,
                'depends_on_value' => NULL,
                'created_at' => '2025-09-17 09:50:55',
                'updated_at' => '2025-09-17 09:52:14',
                'class_name' => NULL,
                'placeholder' => NULL,
            ),
        ));
        
        
    }
}